name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-testpypi:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install setuptools and wheel
        run: |
          python -m pip install --upgrade setuptools wheel
      - name: Build artifact
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish-pypi:
    needs: publish-testpypi
    name: Build and publish Python 🐍 distributions 📦 to PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install setuptools and wheel
        run: |
          python -m pip install --upgrade setuptools wheel
      - name: Build artifact
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          