# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run test file
        run: |
          python3 tests/test.py

  # publish-testpypi:
  #   name: Build and publish Python 🐍 distributions 📦 to TestPyPI

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.7"
  #     - name: Install setuptools and wheel
  #       run: |
  #         python -m pip install --upgrade setuptools wheel
  #     - name: Build artifact
  #       run: |
  #         python setup.py sdist bdist_wheel
  #     - name: Publish distribution 📦 to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         password: ${{ secrets.TESTPYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/
